### ISSUE TITLE
JS Error for config products

### ISSUE THREAD

**Issue by arumcomputer** [firegento/firegento-magesetup2#106]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: 2.0.1
* Magento version: 2.2.2
* PHP version: 7.0.19

### Issue description

Image switch for config products is not working because of JS Error:

Uncaught ReferenceError: mageTemplate is not defined
    at $.(anonymous function).(anonymous function).target._displayTierPriceBlock ({URL}pub/static/version1517667108/frontend/arum/cac/de_DE/FireGento_MageSetup/js/configurable.js:19:21)
    at $.(anonymous function).(anonymous function)._configureElement ({URL}pub/static/version1517667108/frontend/arum/cac/de_DE/Magento_ConfigurableProduct/js/configurable.js:271:18)
    at $.(anonymous function).(anonymous function)._configureElement ({URL}pub/static/version1517667108/frontend/arum/cac/de_DE/jquery/jquery-ui.js:402:25)
    at HTMLSelectElement._configure ({URL}pub/static/version1517667108/frontend/arum/cac/de_DE/Magento_ConfigurableProduct/js/configurable.js:239:24)
    at HTMLSelectElement.<anonymous> ({URL}pub/static/version1517667108/frontend/arum/cac/de_DE/jquery/jquery-ui.js:402:25)
    at HTMLSelectElement.dispatch ({URL}pub/static/version1517667108/frontend/arum/cac/de_DE/jquery.js:5226:27)
    at HTMLSelectElement.elemData.handle ({URL}pub/static/version1517667108/frontend/arum/cac/de_DE/jquery.js:4878:29)

### Steps to reproduce

1. Create Config produtcts with different images for color or size
2. open product in frontend
3. select configurable option for example red t-shirt

**Comment by dmcanna** [comment]
I have also the same issue. To fix the problem we need to update FireGento_MageSetup/js/configurable.js file: add 'mage/template', 'mage/translate', 'priceUtils' to define and add this params in function. Should be so:
`/**
 * Copyright © 2017 FireGento e.V.
 * See LICENSE.md bundled with this module for license details.
 */
define([
    'jquery',
    'mage/template',
    'mage/translate',
    'priceUtils'
], function ($, mageTemplate, $t, priceUtils) {`

**Comment by roman204** [comment]
fixed in d8a848162017885e59cb9341aa8edb2273b1e3d3
