### ISSUE TITLE
ERROR: Wrong request parameters

### ISSUE THREAD

**Issue by code-K** [firegento/firegento-magesetup2#17]
Hi there,

i'm currently running magento2 v 2.0.7 and wanted to do the german magesetup on it.

I'm constantly getting the following error when running the command:
`php bin/magento magesetup:setup:run de`

```$ php bin/magento magesetup:setup:run de
Start setup
Start processor: agreements
Start processor: cms
Wrong request parameters
#0 /srv/users/serverpilot/apps/bodegasavinya/public/vendor/firegento/magesetup2/Model/Setup/SubProcessor/CmsSubProcessor.php(157): Magento\Cms\Model\PageRepository->save(Object(Magento\Cms\Model\Page))
#1 /srv/users/serverpilot/apps/bodegasavinya/public/vendor/firegento/magesetup2/Model/Setup/SubProcessor/CmsSubProcessor.php(88): FireGento\MageSetup\Model\Setup\SubProcessor\CmsSubProcessor->createCmsPage(Array)
#2 /srv/users/serverpilot/apps/bodegasavinya/public/vendor/firegento/magesetup2/Service/SetupService.php(78): FireGento\MageSetup\Model\Setup\SubProcessor\CmsSubProcessor->process(Object(FireGento\MageSetup\Model\Config))
#3 /srv/users/serverpilot/apps/bodegasavinya/public/vendor/firegento/magesetup2/Command/SetupRunCommand.php(155): FireGento\MageSetup\Service\SetupService->execute()
#4 /srv/users/serverpilot/apps/bodegasavinya/public/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): FireGento\MageSetup\Command\SetupRunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /srv/users/serverpilot/apps/bodegasavinya/public/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /srv/users/serverpilot/apps/bodegasavinya/public/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(FireGento\MageSetup\Command\SetupRunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /srv/users/serverpilot/apps/bodegasavinya/public/vendor/magento/framework/Console/Cli.php(49): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /srv/users/serverpilot/apps/bodegasavinya/public/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /srv/users/serverpilot/apps/bodegasavinya/public/bin/magento(25): Symfony\Component\Console\Application->run()
#10 {main}```

Does anyone have any idea how to solve this? So the command will run without issues? 

Apart from that, it'll always display "inkl. 0% MwSt." even if the tax is set to 19%.

Any help is appreciated.

Thanks much and best regards,
Christian

**Comment by therouv** [comment]
Hi @code-K I just tried to reproduce it with Magento 2.0.7 - it seems to work fine. Which PHP version do you use?

**Comment by frostblogNet** [comment]
We will close this issue from 2016. Feel free to reopen if it is relevant.

Thanks
