### ISSUE TITLE
bin/magento magesetup:setup:run de  error

### ISSUE THREAD

**Issue by fanglexue** [firegento/firegento-magesetup2#55]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: x.x.x
* Magento version: x.x.x
* PHP version: 5.6.27
### Issue description

...

### Steps to reproduce

[root@AY131204125836722393Z mage6]# bin/magento magesetup:setup:run de
Start setup
Start processor: agreements
Start processor: cms
Start processor: email
Start processor: systemConfig
Start processor: tax
URL key for specified store already exists.
#0 /usr/local/apache2.2/htdocs/mage6/vendor/magento/framework/Interception/Interceptor.php(74): Magento\UrlRewrite\Model\Storage\AbstractStorage->replace(Array)
#1 /usr/local/apache2.2/htdocs/mage6/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor->___callParent('replace', Array)
#2 /usr/local/apache2.2/htdocs/mage6/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\UrlRewr...', 'replace', Object(Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor), Array, 'storage_plugin')

**Comment by lexwet** [comment]
Same Issue.

Magento v. 2.1.3
PHP v. 7.0.15

```

> user@myhost:~/httpdocs/sandbox/magento2$ php bin/magento magesetup:setup:run de                                                                                                                          Start setup
> Start processor: agreements
> Start processor: cms
> Start processor: email
> Start processor: systemConfig
> Start processor: tax
> URL key for specified store already exists.
> #0 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\UrlRewrite\Model\Storage\AbstractStorage->replace(Array)
> #1 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor->___callParent('replace', Array)
> #2 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\UrlRewr...', 'replace', Object(Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor), Array, 'storage_plugin')
> #3 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/module-catalog-url-rewrite/Model/Category/Plugin/Storage.php(43): Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor->Magento\Framework\Interception\{closure}(Array)
> #4 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\CatalogUrlRewrite\Model\Category\Plugin\Storage->aroundReplace(Object(Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor), Object(Closure), Array)
> #5 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/var/generation/Magento/UrlRewrite/Model/Storage/DbStorage/Interceptor.php(65): Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor->___callPlugins('replace', Array, Array)
> #6 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/module-catalog-url-rewrite/Observer/ProductProcessUrlRewriteSavingObserver.php(61): Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor->replace(Array)
> #7 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\CatalogUrlRewrite\Observer\ProductProcessUrlRewriteSavingObserver->execute(Object(Magento\Framework\Event\Observer))
> #8 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\CatalogUrlRewrite\Observer\ProductProcessUrlRewriteSavingObserver), Object(Magento\Framework\Event\Observer))
> #9 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
> #10 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('catalog_product...', Array)
> #11 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Model/AbstractModel.php(802): Magento\Framework\Event\Manager\Proxy->dispatch('catalog_product...', Array)
> #12 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/module-catalog/Model/Product.php(921): Magento\Framework\Model\AbstractModel->afterSave()
> #13 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/var/generation/Magento/Catalog/Model/Product/Interceptor.php(362): Magento\Catalog\Model\Product->afterSave()
> #14 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/EntityManager/Observer/AfterEntitySave.php(34): Magento\Catalog\Model\Product\Interceptor->afterSave()
> #15 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\Framework\EntityManager\Observer\AfterEntitySave->execute(Object(Magento\Framework\Event\Observer))
> #16 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Framework\EntityManager\Observer\AfterEntitySave), Object(Magento\Framework\Event\Observer))
> #17 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
> #18 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('magento_catalog...', Array)
> #19 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/EntityManager/EventManager.php(53): Magento\Framework\Event\Manager\Proxy->dispatch('magento_catalog...', Array)
> #20 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/EntityManager/Operation/Update.php(108): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent('Magento\\Catalog...', 'save_after', Array)
> #21 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/EntityManager/EntityManager.php(87): Magento\Framework\EntityManager\Operation\Update->execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)
> #22 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/module-catalog/Model/ResourceModel/Product.php(695): Magento\Framework\EntityManager\EntityManager->save(Object(Magento\Catalog\Model\Product\Interceptor))
> #23 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Catalog\Model\ResourceModel\Product->save(Object(Magento\Catalog\Model\Product\Interceptor))
> #24 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent('save', Array)
> #25 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'save', Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Array, 'clean_cache')
> #26 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/App/Cache/FlushCacheByTags.php(71): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
> #27 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\App\Cache\FlushCacheByTags->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
> #28 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'save', Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Array, 'catalogsearchFu...')
> #29 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(51): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
> #30 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(24): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
> #31 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
> #32 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'save', Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Array, 'apply_catalog_r...')
> #33 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/module-catalog-rule/Plugin/Indexer/Product/Save/ApplyRules.php(40): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
> #34 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\CatalogRule\Plugin\Indexer\Product\Save\ApplyRules->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
> #35 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(273): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins('save', Array, Array)
> #36 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Model/AbstractModel.php(631): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor))
> #37 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/var/generation/Magento/Catalog/Model/Product/Interceptor.php(2364): Magento\Framework\Model\AbstractModel->save()
> #38 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/app/code/FireGento/MageSetup/Model/Setup/SubProcessor/TaxSubProcessor.php(267): Magento\Catalog\Model\Product\Interceptor->save()
> #39 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/app/code/FireGento/MageSetup/Model/Setup/SubProcessor/TaxSubProcessor.php(167): FireGento\MageSetup\Model\Setup\SubProcessor\TaxSubProcessor->saveTaxClassRelations(Array)
> #40 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/app/code/FireGento/MageSetup/Service/SetupService.php(78): FireGento\MageSetup\Model\Setup\SubProcessor\TaxSubProcessor->process(Object(FireGento\MageSetup\Model\Config))
> #41 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/app/code/FireGento/MageSetup/Command/SetupRunCommand.php(160): FireGento\MageSetup\Service\SetupService->execute()
> #42 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): FireGento\MageSetup\Command\SetupRunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #43 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #44 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(FireGento\MageSetup\Command\SetupRunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #45 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/magento/framework/Console/Cli.php(96): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #46 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #47 /var/www/vhosts/myhost/httpdocs/sandbox/magento2/bin/magento(23): Symfony\Component\Console\Application->run()
> #48 {main}

```

**Comment by michael-hxx** [comment]
I got the same error with Magento 2.1.4 and PHP 5.6.30

**Comment by PhiIipp** [comment]
Hello,
have same problem with 2.1.6 and php  7.0.17 . I  Installed 2.0.x and upgraded to 2.1..
I also have products already created and some content pages.

Which URLs are required/used by firegento ? Maybe i can remove them before installing magesetup2 ?

`/httpdocs$ bin/magento magesetup:setup:run de
Start setup
Start processor: agreements
Start processor: cms
Start processor: email
Start processor: systemConfig
Start processor: tax
URL key for specified store already exists.
URL key for specified store already exists.
#0 /var/www/vhosts/tarnava.ro/httpdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\UrlRewrite\Model\Storage\AbstractStorage->replace(Array)
#1 /var/www/vhosts/tarnava.ro/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\UrlRewrite\Model\Storage\DbStorage\Interceptor->___callParent('replace', Array)`

Thanks,
Philipp

**Comment by sonjaka** [comment]
Did anyone have a solution for this? I'm having the same problem running Magento 2.1.6.

**Comment by codedge** [comment]
This seems to be a more general issue happening also after product imports. There is an open issue in the Magento issue tracker: https://github.com/magento/magento2/issues/6671

I think we need to wait till Magento fixed this issue - not related to Firegento-MageSetup2 directly.

**Comment by addiman** [comment]
same issue here. anyone has a solution?

**Comment by addiman** [comment]
still same issue with magento 2.2.2. anyone can provide help?
The magnto 6671 issue is solved, but i have still that problem.

**Comment by ulicodex** [comment]
2.2.2 Me too.

**Comment by simple-web-solutions** [comment]
why is that issue closed? There are persons here, having that problem. I do have it as well in a shop with 2.2.4. no fresh install, so products and categories was in the shop before magesetup

**Comment by mautz-et-tong** [comment]
First:
This issue here is not closed. If you refer to the magento 2 issue, ask them or better reopen the issue there following their guidelines.
Second:
As codedge mentioned, that error is coming from a core process. While saving the products after the tax was changed on this product. So maybe this module started the process which leads to the error, but the error is thrown in the core. I think, you should have other problems regarding products, if you have this error, too.
The error message "URL key for specified store already exists." points to the direction of empty (not generated) url keys or a url key which will be a duplicate if generated.

**Comment by tf25** [comment]
Same issue for magento 2.2.5
anyone has a solution?

**Comment by dev-waltr** [comment]
Still had the same issue.
A quick-fix:
in: FireGento\MageSetup\Model\Setup\SubProcessor\TaxSubProcessor in function: saveTaxClassRelations

replace the code:
`$product->setData('tax_class_id', $productTaxClassId);`
`$product->save();`

with following:
`$productModel = $this->productFactory->create();`
`$productModel->getResource()->load($productModel, $product->getEntityId());`
`$productModel->setData('tax_class_id', $productTaxClassId);`
`$productModel->getResource()->save($productModel);`

I tested it on Magento 2.2.5 + Sample Data. The issue is, that the loaded data in the model isn't the same as the one saved in the DB. The product that fails was: Sprite Stasis Ball 55 cm - 24-WG081-pink  (e.g. visibility: 4 in Model but 1 in DB).

The quick-fix isn't an optimize solution but it works. It is a memory-consuming task and you have to consider it when running the code.
